#!/bin/sh /etc/rc.common
# Copyright (C) 2012 Gui Iribarren
# Copyright (C) 2017 Daniel Golle
# This is free software, licensed under the GNU General Public License v3.

START=99
USE_PROCD=1
PROG=/usr/bin/monitor_network

start_service() {
    logger -p user.info -t "monitor_network" "starting"
    
    procd_open_instance
	procd_set_param command $PROG
	procd_set_param stderr 1
	procd_close_instance
}